// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

Future<void> goShopping(
        {required String name,
        required String location,
        required FutureOr<void> Function(String) onThere,
        dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGoShopping(
        name: name, location: location, onThere: onThere, hint: hint);
