// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.36.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> tonRequest(
        {required int context,
        required String functionName,
        required String functionParamsJson,
        dynamic hint}) =>
    RustLib.instance.api.crateApiTonTonRequest(
        context: context,
        functionName: functionName,
        functionParamsJson: functionParamsJson,
        hint: hint);

Future<String> tonCreateContext({required String config, dynamic hint}) =>
    RustLib.instance.api
        .crateApiTonTonCreateContext(config: config, hint: hint);
